<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://logic.service.serialisation.formation.ocp.fr/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://service.serialisation.formation.ocp.fr/" name="RefProductLogicService" targetNamespace="http://logic.service.serialisation.formation.ocp.fr/">
  <wsdl:import location="refType.wsdl" namespace="http://service.serialisation.formation.ocp.fr/">
    </wsdl:import>
  <wsdl:binding name="RefProductLogicServiceSoapBinding" type="ns1:RefProduct">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="addProduct">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="addProduct">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="addProductResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="AlreadyExistProductException">
        <soap:fault name="AlreadyExistProductException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getRef">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getRef">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getRefResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="UnknownProductException">
        <soap:fault name="UnknownProductException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="updateProduct">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="updateProduct">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateProductResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="UnknownProductException">
        <soap:fault name="UnknownProductException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getAll">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getAll">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getAllResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="unReference">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="unReference">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="unReferenceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="UnknownProductException">
        <soap:fault name="UnknownProductException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RefProductLogicService">
    <wsdl:port binding="tns:RefProductLogicServiceSoapBinding" name="RefProductLogicPort">
      <soap:address location="http://dev.valuetis.fr/serialisation/ref"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>